import { Position, Project, SkillCategory, Technology } from "./types";

export const titles = ["Software Engineer 🚀", "Full-stack Web Developer 🌐", "Front-end Developer ✨", "Back-end Developer 🛠"];
export const projectCategories = ["all", "website", "application", "plugin / package", "mobile"] as const;
export const projectModalTabs = ["overview", "gallery"] as const;

export const projects: Project[] = [
  {
    title: "Custom Quoter Business Management System",
    description: "A business management system specialized in landscaping industry.",
    longDescription: "A business management system specialized in landscaping industry built with Laravel, jQuery, and Bootstrap.",
    technologies: ["laravel", "jquery", "bootstrap"],
    category: ["application"],
    type: "Maintenance & Feature Development",
    thumbnail: "/images/projects/cqbms-thumbnail.png",
    link: "https://www.cq-business-management-software.com/",
    features: ["Dynamic Scheduling", "Assets management", "Leads management", "Ticketing system"],
    images: ["/images/projects/cqbms-thumbnail.png", "/images/projects/cqbms-calendar.png"],
  },
  {
    title: "RealtyWalk",
    description: "An interactive map for properties in Houston, TX.",
    longDescription: "An interactive map for properties in Houston, TX built with Laravel, Bootstrap, and Vue.js.",
    technologies: ["laravel", "vue", "typescript", "javascript", "bootstrap"],
    category: ["application"],
    type: "Maintenance & Feature Development",
    status: "ongoing",
    link: "https://realtywalk.com",
    features: ["Placement management", "Property management", "Hotel management", "Alerts management", "Report generation"],
    thumbnail: "/images/projects/rw-thumbnail.png",
    images: ["/images/projects/rw-thumbnail.png"],
  },
  {
    title: "Cypress Green",
    description: "A modern real estate website showcasing a master-planned community in Tomball, TX.",
    longDescription:
      "A comprehensive real estate website built for Cypress Green, featuring property listings, community information, and interactive features. The site highlights the community's amenities, homebuilders, and lifestyle offerings while providing an intuitive user experience for potential residents.",
    technologies: ["wordpress", "php", "javascript"],
    category: ["website"],
    thumbnail: "/images/projects/cypress-green-home.png",
    images: [
      "/images/projects/cypress-green-home.png",
      "/images/projects/cypress-green-location.png",
      "/images/projects/cypress-green-location-open.png",
    ],
    link: "https://cypressgreentx.com/",
    features: [
      "Interactive community map",
      "Property listings and home designs",
      "Amenity information and virtual tours",
      "Homebuilder profiles and floor plans",
      "Beautiful transitions and animations",
      "Responsive design for all devices",
    ],
    type: "End-to-End Development",
    status: "completed",
    completionDate: "2022-10",
  },
  {
    title: "JAE Data Management",
    description:
      "A professional data management and business services company website showcasing their expertise in data processing, graphic design, and virtual assistance.",
    longDescription:
      "A comprehensive business website built with Joomla and Gantry 5 framework, featuring services in databasing, skiptracing, graphic design, data analysis, and virtual assistance. The site effectively presents the company's diverse service offerings and client testimonials.",
    technologies: ["joomla", "jquery", "javascript"],
    category: ["website"],
    type: "End-to-End Development",
    completionDate: "2014-09",
    link: "https://jaedatamanagement.com",
    features: [
      "Service Portfolio Showcase",
      "Client Testimonials",
      "Contact Information Management",
      "Responsive Design",
      "SEO Optimization",
      "Performance Optimization",
      "Multi-page Navigation",
      "Image Gallery",
    ],
    thumbnail: "/images/projects/jae-home.png",
    images: ["/images/projects/jae-home.png", "/images/projects/jae-portfolio.png"],
  },
  {
    title: "TPS Housing",
    description: "A property management system for temporary housing solutions company.",
    longDescription: "A property management system for temporary housing solutions company built with Laravel, Bootstrap, jQuery, and Vue.js.",
    technologies: ["laravel", "vue", "typescript", "javascript", "bootstrap"],
    category: ["application"],
    type: "Maintenance & Feature Development",
    status: "ongoing",
    link: "https://tpshousing.com",
    features: ["Placement management", "Property management", "Hotel management", "Alerts management", "Report generation"],
    thumbnail: "/images/projects/tps-thumbnail.png",
    images: ["/images/projects/tps-thumbnail.png", "/images/projects/tps-bizdev.png"],
  },
  {
    title: "React Mouse Trail",
    description: "A customizable mouse trail effect component for React applications.",
    longDescription:
      "A lightweight and flexible React component that creates beautiful mouse trail effects. Built with Framer Motion, it offers smooth animations, customizable styles, and easy integration into any React project. Perfect for adding engaging interactive elements to web applications.",
    technologies: ["react", "typescript", "javascript"],
    category: ["plugin / package"],
    thumbnail: "/images/projects/react-mouse-trail-thumbnail.png",
    images: ["/images/projects/react-mouse-trail-thumbnail.png"],
    link: "https://www.npmjs.com/package/@pjsalita/react-mouse-trail/",
    githubLink: "https://github.com/pjsalita/react-mouse-trail",
    features: [
      "Smooth trail animations using Framer Motion",
      "Customizable trail styles and colors",
      "Configurable trail length and delay",
      "TypeScript support",
      "Easy to integrate",
    ],
    type: "End-to-End Development",
    status: "completed",
    completionDate: "2022-06",
  },
  {
    title: "XYZ Figlet",
    description: "A simple ASCII art generator.",
    longDescription: "A web-based ASCII art generator that transforms text into beautiful ASCII art.",
    technologies: ["vue", "laravel", "javascript"],
    category: ["application"],
    thumbnail: "/images/projects/xyz-figlet-thumbnail.png",
    images: ["/images/projects/xyz-figlet-thumbnail.png", "/images/projects/xyz-figlet-login.png", "/images/projects/xyz-figlet-log.png"],
    link: "https://xyz.pjsalita.com/",
    githubLink: "https://github.com/pjsalita/xyz",
    features: ["ASCII art using O character", "Customize size and characters to print", "Store results to log file", "Simple authentication"],
    type: "End-to-End Development",
    status: "completed",
    completionDate: "2020-08",
  },
  {
    title: "Pelco Reminder App",
    description: "A comprehensive bill reminder system for electricity consumers with SMS and push notifications.",
    longDescription:
      "A full-stack application designed for Pelco, an electricity provider company, featuring a web-based admin panel and a mobile app for consumers. The system helps consumers stay informed about their electricity bills through SMS reminders and push notifications, while administrators can efficiently manage consumer data and notification schedules.",
    technologies: ["laravel", "react", "typescript", "javascript", "bootstrap", "livewire", "ionic"],
    category: ["application", "mobile"],
    thumbnail: "/images/projects/pelco-thumbnail.png",
    images: ["/images/projects/pelco-thumbnail.png", "/images/projects/pelco-dashboard.png", "/images/projects/pelco-data.png"],
    mobileImages: [
      "/images/projects/pelco-intro-1.jpg",
      "/images/projects/pelco-intro-2.jpg",
      "/images/projects/pelco-intro-3.jpg",
      "/images/projects/pelco-intro-4.jpg",
      "/images/projects/pelco-login.jpg",
    ],
    features: [
      "Web-based admin dashboard",
      "Mobile app for consumers",
      "SMS bill reminders",
      "Firebase push notifications",
      "Consumer bill history",
      "Payment tracking",
      "Notification scheduling",
      "User authentication",
      "Real-time updates",
      "Offline support",
    ],
    type: "End-to-End Development",
    status: "completed",
    completionDate: "2022-01",
  },
];

export const positions: Position[] = [
  {
    title: "Lead Laravel Developer",
    company: "Appy World Ltd.",
    location: "London, UK",
    startDate: "Sept 2024",
    endDate: "Present",
    description: ["Implement features and fix bugs of live application", "Deploy and manage staging and production servers"],
    technologies: ["laravel", "php", "jquery", "bootstrap", "rds", "ec2", "s3"],
  },
  {
    title: "Full-stack Web Developer",
    company: "Nytrobit Labs LLC.",
    location: "Texas, USA",
    startDate: "Sept 2022",
    endDate: "Sept 2024",
    description: ["Create landing pages and web applications", "Deploy and manage web applications on own servers"],
    technologies: ["laravel", "php", "vue", "wordpress", "javascript", "mysql", "postgresql", "shopify"],
  },
  {
    title: "Software Engineer",
    company: "98Labs Inc.",
    location: "Makati, PH",
    startDate: "Sept 2020",
    endDate: "Sept 2022",
    description: ["Implement new features, ideas, and bug fixes on web and mobile systems"],
    technologies: ["node", "angular", "ionic", "mongodb", "nextjs", "react", "javascript"],
  },
  {
    title: "Freelance Web Developer",
    company: "Upwork",
    location: "Remote",
    startDate: "Jan 2020",
    endDate: "Oct 2020",
    description: ["Server setup and maintenance, bug fixing, feature implementation", "Database design, code optimization and refactoring"],
    technologies: ["angular", "vue", "laravel", "php", "python", "nginx", "apache2", "aws"],
  },
  {
    title: "Web Developer",
    company: "iPhiTech IT and Digital Solutions Corporation",
    location: "Pampanga, PH",
    startDate: "Feb 2019",
    endDate: "Jan 2020",
    description: [
      "Worked with various projects in PHP, Laravel, ReactJS, WordPress, and Shopify",
      "Set up and manage instances in AWS, GCP, and DigitalOcean",
    ],
    technologies: ["php", "laravel", "react", "wordpress", "joomla", "shopify", "jquery", "aws", "gcp", "digitalocean"],
  },
];

export const skills: SkillCategory[] = [
  {
    title: "Backend",
    skills: ["laravel", "php", "node", "express", "livewire", "typescript"],
  },
  {
    title: "Frontend",
    skills: [
      "vue",
      "react",
      "nextjs",
      "angular",
      "ionic",
      "inertia",
      "tailwind",
      "bootstrap",
      "sass",
      "css",
      "html",
      "javascript",
      "typescript",
      "jquery",
    ],
  },
  {
    title: "Databases",
    skills: ["mysql", "postgresql", "mongodb"],
  },
  {
    title: "Cloud & DevOps",
    skills: ["aws", "gcp", "digitalocean", "docker", "git"],
  },
  {
    title: "CMS & Platforms",
    skills: ["wordpress", "shopify", "joomla"],
  },
];

export const skillTechMap: Record<Technology, { label: string; bg: string; text: string }> = {
  laravel: {
    label: "Laravel",
    bg: "bg-[#FF2D20]/15 hover:bg-[#FF2D20]/25",
    text: "text-[#FF2D20]",
  },
  php: {
    label: "PHP",
    bg: "bg-[#777BB3]/15 hover:bg-[#777BB3]/25",
    text: "text-[#232531] dark:text-[#777BB3]",
  },
  node: {
    label: "Node.js",
    bg: "bg-[#539E43]/15 hover:bg-[#539E43]/25",
    text: "text-[#215732] dark:text-[#539E43]",
  },
  express: {
    label: "Express.js",
    bg: "bg-[#000000]/15 hover:bg-[#000000]/25",
    text: "text-[#000000] dark:text-[#FFFFFF]",
  },
  livewire: {
    label: "Livewire",
    bg: "bg-[#FB70A9]/15 hover:bg-[#FB70A9]/25",
    text: "text-[#FB70A9]",
  },
  typescript: {
    label: "TypeScript",
    bg: "bg-[#3178C6]/15 hover:bg-[#3178C6]/25",
    text: "text-[#3178C6]",
  },
  react: {
    label: "React",
    bg: "bg-[#087EA4]/20 hover:bg-[#087EA4]/30",
    text: "text-[#087EA4] dark:text-[#149ECA]",
  },
  nextjs: {
    label: "Next.js",
    bg: "bg-[#000000]/15 hover:bg-[#000000]/25",
    text: "text-[#000000] dark:text-[#FFFFFF]",
  },
  angular: {
    label: "Angular",
    bg: "bg-[#DD0031]/15 hover:bg-[#DD0031]/25",
    text: "text-[#DD0031]",
  },
  ionic: {
    label: "Ionic",
    bg: "bg-[#3880FF]/15 hover:bg-[#3880FF]/25",
    text: "text-[#3880FF]",
  },
  inertia: {
    label: "Inertia.js",
    bg: "bg-[#5A67D8]/15 hover:bg-[#5A67D8]/25",
    text: "text-[#5A67D8]",
  },
  tailwind: {
    label: "Tailwind CSS",
    bg: "bg-[#38BDF8]/15 hover:bg-[#38BDF8]/25",
    text: "text-[#0F172A] dark:text-[#38BDF8]",
  },
  bootstrap: {
    label: "Bootstrap",
    bg: "bg-[#7952B3]/15 hover:bg-[#7952B3]/25",
    text: "text-[#7952B3]",
  },
  sass: {
    label: "Sass",
    bg: "bg-[#CC6699]/15 hover:bg-[#CC6699]/25",
    text: "text-[#CC6699]",
  },
  css: {
    label: "CSS",
    bg: "bg-[#264DE4]/15 hover:bg-[#264DE4]/25",
    text: "text-[#264DE4]",
  },
  html: {
    label: "HTML",
    bg: "bg-[#E34C26]/15 hover:bg-[#E34C26]/25",
    text: "text-[#E34C26]",
  },
  javascript: {
    label: "JavaScript",
    bg: "bg-[#F7DF1E]/15 hover:bg-[#F7DF1E]/25",
    text: "text-[#000000] dark:text-[#F7DF1E]",
  },
  jquery: {
    label: "jQuery",
    bg: "bg-[#0769AD]/15 hover:bg-[#0769AD]/25",
    text: "text-[#0769AD]",
  },
  mysql: {
    label: "MySQL",
    bg: "bg-[#00758F]/15 hover:bg-[#00758F]/25",
    text: "text-[#00758F]",
  },
  postgresql: {
    label: "PostgreSQL",
    bg: "bg-[#336791]/15 hover:bg-[#336791]/25",
    text: "text-[#336791]",
  },
  mongodb: {
    label: "MongoDB",
    bg: "bg-[#13AA52]/15 hover:bg-[#13AA52]/25",
    text: "text-[#13AA52]",
  },
  aws: {
    label: "AWS",
    bg: "bg-[#FF9900]/15 hover:bg-[#FF9900]/25",
    text: "text-[#FF9900]",
  },
  docker: {
    label: "Docker",
    bg: "bg-[#2496ED]/15 hover:bg-[#2496ED]/25",
    text: "text-[#2496ED]",
  },
  git: {
    label: "Git",
    bg: "bg-[#F1502F]/15 hover:bg-[#F1502F]/25",
    text: "text-[#F1502F]",
  },
  wordpress: {
    label: "WordPress",
    bg: "bg-[#21759B]/15 hover:bg-[#21759B]/25",
    text: "text-[#21759B]",
  },
  shopify: {
    label: "Shopify",
    bg: "bg-[#95BF47]/15 hover:bg-[#95BF47]/25",
    text: "text-[#004C3F] dark:text-[#95BF47]",
  },
  joomla: {
    label: "Joomla",
    bg: "bg-[#1E3B70]/15 hover:bg-[#1E3B70]/25",
    text: "text-[#1E3B70] dark:text-[#4A90E2]",
  },
  vue: {
    label: "Vue",
    bg: "bg-[#42B883]/15 hover:bg-[#42B883]/25",
    text: "text-[#34495E] dark:text-[#42B883]",
  },
  rds: {
    label: "RDS",
    bg: "bg-[#527FFF]/15 hover:bg-[#527FFF]/25",
    text: "text-[#527FFF]",
  },
  ec2: {
    label: "EC2",
    bg: "bg-[#FF9900]/15 hover:bg-[#FF9900]/25",
    text: "text-[#FF9900]",
  },
  s3: {
    label: "S3",
    bg: "bg-[#569A31]/15 hover:bg-[#569A31]/25",
    text: "text-[#569A31]",
  },
  python: {
    label: "Python",
    bg: "bg-[#3776AB]/15 hover:bg-[#3776AB]/25",
    text: "text-[#3776AB]",
  },
  nginx: {
    label: "Nginx",
    bg: "bg-[#009639]/15 hover:bg-[#009639]/25",
    text: "text-[#009639]",
  },
  apache2: {
    label: "Apache",
    bg: "bg-[#D22128]/15 hover:bg-[#D22128]/25",
    text: "text-[#D22128]",
  },
  gcp: {
    label: "GCP",
    bg: "bg-[#4285F4]/15 hover:bg-[#4285F4]/25",
    text: "text-[#4285F4]",
  },
  digitalocean: {
    label: "DigitalOcean",
    bg: "bg-[#0080FF]/15 hover:bg-[#0080FF]/25",
    text: "text-[#0080FF]",
  },
};
