import { Project } from './types';

export const titles = ['Software Engineer 🚀', 'Full-stack Web Developer 🌐', 'Front-end Developer ✨', 'Back-end Developer 🛠'];
export const projectCategories = ['all', 'website', 'application', 'plugin / package', 'mobile'] as const;
export const projectModalTabs = ['overview', 'gallery'] as const;

export const projects: Project[] = [
  {
    title: 'Cypress Green',
    description: 'A modern real estate website showcasing a master-planned community in Tomball, TX.',
    longDescription:
      "A comprehensive real estate website built for Cypress Green, featuring property listings, community information, and interactive features. The site highlights the community's amenities, homebuilders, and lifestyle offerings while providing an intuitive user experience for potential residents.",
    technologies: ['wordpress', 'php', 'javascript'],
    category: ['website'],
    thumbnail: '/images/projects/cypress-green-home.png',
    images: [
      '/images/projects/cypress-green-home.png',
      '/images/projects/cypress-green-location.png',
      '/images/projects/cypress-green-location-open.png',
    ],
    link: 'https://cypressgreentx.com/',
    features: [
      'Interactive community map',
      'Property listings and home designs',
      'Amenity information and virtual tours',
      'Homebuilder profiles and floor plans',
      'Beautiful transitions and animations',
      'Responsive design for all devices',
    ],
    type: 'End-to-End Development',
    status: 'completed',
    completionDate: '2022-10',
  },
  {
    title: 'JAE Data Management',
    description:
      'A professional data management and business services company website showcasing their expertise in data processing, graphic design, and virtual assistance.',
    longDescription:
      "A comprehensive business website built with Joomla and Gantry 5 framework, featuring services in databasing, skiptracing, graphic design, data analysis, and virtual assistance. The site effectively presents the company's diverse service offerings and client testimonials.",
    technologies: ['joomla', 'jquery', 'javascript'],
    category: ['website'],
    type: 'End-to-End Development',
    completionDate: '2014-09',
    link: 'https://jaedatamanagement.com',
    features: [
      'Service Portfolio Showcase',
      'Client Testimonials',
      'Contact Information Management',
      'Responsive Design',
      'SEO Optimization',
      'Performance Optimization',
      'Multi-page Navigation',
      'Image Gallery',
    ],
    thumbnail: '/images/projects/jae-home.png',
    images: ['/images/projects/jae-home.png', '/images/projects/jae-portfolio.png'],
  },
  {
    title: 'RealtyWalk',
    description: 'An interactive map for properties in Houston, TX.',
    longDescription: 'An interactive map for properties in Houston, TX built with Laravel, Bootstrap, and Vue.js.',
    technologies: ['laravel', 'vue', 'typescript', 'javascript', 'bootstrap'],
    category: ['application'],
    type: 'Maintenance & Feature Development',
    status: 'ongoing',
    link: 'https://realtywalk.com',
    features: ['Placement management', 'Property management', 'Hotel management', 'Alerts management', 'Report generation'],
    thumbnail: '/images/projects/rw-thumbnail.png',
    images: ['/images/projects/rw-thumbnail.png'],
  },
  {
    title: 'TPS Housing',
    description: 'A property management system for temporary housing solutions company.',
    longDescription: 'A property management system for temporary housing solutions company built with Laravel, Bootstrap, jQuery, and Vue.js.',
    technologies: ['laravel', 'vue', 'typescript', 'javascript', 'bootstrap'],
    category: ['application'],
    type: 'Maintenance & Feature Development',
    status: 'ongoing',
    link: 'https://tpshousing.com',
    features: ['Placement management', 'Property management', 'Hotel management', 'Alerts management', 'Report generation'],
    thumbnail: '/images/projects/tps-thumbnail.png',
    images: ['/images/projects/tps-thumbnail.png', '/images/projects/tps-bizdev.png'],
  },
  {
    title: 'Custom Quoter Business Management System',
    description: 'A business management system specialized in landscaping industry.',
    longDescription: 'A business management system specialized in landscaping industry built with Laravel, jQuery, and Bootstrap.',
    technologies: ['laravel', 'jquery', 'bootstrap'],
    category: ['application'],
    type: 'Maintenance & Feature Development',
    thumbnail: '/images/projects/cqbms-thumbnail.png',
    link: 'https://www.cq-business-management-software.com/',
    features: ['Dynamic Scheduling', 'Assets management', 'Leads management', 'Ticketing system'],
    images: ['/images/projects/cqbms-thumbnail.png', '/images/projects/cqbms-calendar.png'],
  },
  {
    title: 'React Mouse Trail',
    description: 'A customizable mouse trail effect component for React applications.',
    longDescription:
      'A lightweight and flexible React component that creates beautiful mouse trail effects. Built with Framer Motion, it offers smooth animations, customizable styles, and easy integration into any React project. Perfect for adding engaging interactive elements to web applications.',
    technologies: ['react', 'typescript', 'javascript'],
    category: ['plugin / package'],
    thumbnail: '/images/projects/react-mouse-trail-thumbnail.png',
    images: ['/images/projects/react-mouse-trail-thumbnail.png'],
    link: 'https://www.npmjs.com/package/@pjsalita/react-mouse-trail/',
    githubLink: 'https://github.com/pjsalita/react-mouse-trail',
    features: [
      'Smooth trail animations using Framer Motion',
      'Customizable trail styles and colors',
      'Configurable trail length and delay',
      'TypeScript support',
      'Easy to integrate',
    ],
    type: 'End-to-End Development',
    status: 'completed',
    completionDate: '2022-06',
  },
  {
    title: 'XYZ Figlet',
    description: 'A simple ASCII art generator.',
    longDescription: 'A web-based ASCII art generator that transforms text into beautiful ASCII art.',
    technologies: ['vue', 'laravel', 'javascript'],
    category: ['application'],
    thumbnail: '/images/projects/xyz-figlet-thumbnail.png',
    images: ['/images/projects/xyz-figlet-thumbnail.png', '/images/projects/xyz-figlet-login.png', '/images/projects/xyz-figlet-log.png'],
    link: 'https://xyz.pjsalita.com/',
    githubLink: 'https://github.com/pjsalita/xyz',
    features: ['ASCII art using O character', 'Customize size and characters to print', 'Store results to log file', 'Simple authentication'],
    type: 'End-to-End Development',
    status: 'completed',
    completionDate: '2020-08',
  },
  {
    title: 'Pelco Reminder App',
    description: 'A comprehensive bill reminder system for electricity consumers with SMS and push notifications.',
    longDescription:
      'A full-stack application designed for Pelco, an electricity provider company, featuring a web-based admin panel and a mobile app for consumers. The system helps consumers stay informed about their electricity bills through SMS reminders and push notifications, while administrators can efficiently manage consumer data and notification schedules.',
    technologies: ['laravel', 'react', 'typescript', 'javascript', 'bootstrap', 'livewire', 'ionic'],
    category: ['application', 'mobile'],
    thumbnail: '/images/projects/pelco-thumbnail.png',
    images: ['/images/projects/pelco-thumbnail.png', '/images/projects/pelco-dashboard.png', '/images/projects/pelco-data.png'],
    mobileImages: [
      '/images/projects/pelco-intro-1.jpg',
      '/images/projects/pelco-intro-2.jpg',
      '/images/projects/pelco-intro-3.jpg',
      '/images/projects/pelco-intro-4.jpg',
      '/images/projects/pelco-login.jpg',
    ],
    features: [
      'Web-based admin dashboard',
      'Mobile app for consumers',
      'SMS bill reminders',
      'Firebase push notifications',
      'Consumer bill history',
      'Payment tracking',
      'Notification scheduling',
      'User authentication',
      'Real-time updates',
      'Offline support',
    ],
    type: 'End-to-End Development',
    status: 'completed',
    completionDate: '2022-01',
  },
];
